CREATE DATABASE quan_ly_xuat_nhap_vat_tu;
USE quan_ly_xuat_nhap_vat_tu;

CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE NHACC (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(100),
    DiaChi VARCHAR(200),
    SDT VARCHAR(15)
);

CREATE TABLE VATTU (
    MaVTU VARCHAR(10) PRIMARY KEY,
    TenVTU VARCHAR(100),
    MaNCC VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE DONDH (
    SoDH VARCHAR(10) PRIMARY KEY,
    NgayDH DATE
);

CREATE TABLE CTPHIEUXUAT (
    SoPX VARCHAR(10),
    MaVTU VARCHAR(10),
    DGXuat FLOAT,
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CTPHIEUNHAP (
    SoPN VARCHAR(10),
    MaVTU VARCHAR(10),
    DGNhap FLOAT,
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CTDONDH (
    SoDH VARCHAR(10),
    MaVTU VARCHAR(10),
    SLDat INT,
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
